import type { WorkflowUiResult } from "../services/api";

export const nasaReplay: WorkflowUiResult = {
  diagnosis:
    "Risk is low. Cycle 31 closed for FD001 unit 1 under known HPC degradation conditions. The system keeps the asset in monitoring mode, validates RUL 112, and opens a review ticket with retrieved evidence.",
  riskLevel: "low",
  situation: {
    scenarioName: "Autonomous turbofan health gate replay",
    trigger: "Cycle 31 telemetry window closed",
    physicalCondition: "FD001 unit 1 has completed its latest observed cycle under known HPC degradation conditions.",
    decisionRequired: "Decide whether to keep monitoring or open a maintenance review.",
    qdrantRole: "Retrieve operating context, RUL semantics, and maintenance policy from domain documents with source-backed provenance.",
    assetType: "turbofan_engine",
    faultMode: "HPC degradation",
    operatingCondition: "one condition, sea level",
    signalWindow: [
      { cycle: 27, sensor_2: 642.08, sensor_3: 1586.65, sensor_4: 1400.31, sensor_11: 47.34, sensor_15: 8.4494 },
      { cycle: 28, sensor_2: 641.93, sensor_3: 1594.25, sensor_4: 1401.29, sensor_11: 47.05, sensor_15: 8.4470 },
      { cycle: 29, sensor_2: 641.95, sensor_3: 1587.15, sensor_4: 1398.11, sensor_11: 47.42, sensor_15: 8.4212 },
      { cycle: 30, sensor_2: 642.79, sensor_3: 1585.72, sensor_4: 1400.97, sensor_11: 47.4, sensor_15: 8.411 },
      { cycle: 31, sensor_2: 642.58, sensor_3: 1581.22, sensor_4: 1398.91, sensor_11: 47.23, sensor_15: 8.4024 },
    ],
  },
  validation: {
    passed: true,
    expected: { groundTruthRul: 112 },
    expectedFailureCycle: 143,
  },
  trace: [
    { step: "load_signals", summary: "Loaded FD001 unit 1 telemetry snapshot." },
    { step: "retrieve_docs", summary: "Retrieved NASA C-MAPSS reference evidence." },
    { step: "compute_baseline", summary: "Computed deterministic RUL baseline." },
    { step: "ai_diagnose", summary: "Generated structured diagnosis path." },
    { step: "validate_expected", summary: "Matched RUL 112 and failure cycle 143." },
    { step: "create_ticket", summary: "Created operational review ticket." },
  ],
  sources: [
    {
      chunkId: "cmapss-reference-rul-1",
      path: "documents/cmapss_reference.md",
      title: "NASA C-MAPSS and FD001 Reference",
      sectionTitle: "Remaining useful life meaning",
      sourceLabel: "NASA DASHlink and NASA NTRS",
      sourceUrl: "https://c3.ndc.nasa.gov/dashlink/resources/139/",
      sourceUrls: [
        "https://c3.ndc.nasa.gov/dashlink/resources/139/",
        "https://c3.ndc.nasa.gov/dashlink/resources/14/",
        "https://ntrs.nasa.gov/api/citations/20120007104/downloads/20120007104.pdf",
        "https://ntrs.nasa.gov/api/citations/20205001125/downloads/Run_to_Failure_Simulation_Under_Real_Flight_Conditions_Dataset.pdf",
      ],
      sourceAuthority: "nasa_official",
      sourceType: "nasa",
      excerpt: "Remaining useful life is remaining cycles from last observed point until simulated failure, and FD001 labels keep that meaning for each test trajectory.",
      rank: 1,
      provider: "fastembed",
      score: 1.4,
    },
    {
      chunkId: "health-gate-policy-1",
      path: "documents/health_gate_policy.md",
      title: "FD001 Health Gate Framing",
      sectionTitle: "Evidence fields worth carrying with gate result",
      sourceLabel: "NASA DASHlink, NASA NTRS, and repo-pinned FD001 micro-sample",
      sourceUrl: "https://c3.ndc.nasa.gov/dashlink/resources/14/",
      sourceUrls: [
        "https://c3.ndc.nasa.gov/dashlink/resources/14/",
        "https://c3.ndc.nasa.gov/dashlink/resources/139/",
        "https://ntrs.nasa.gov/api/citations/20205001125/downloads/Run_to_Failure_Simulation_Under_Real_Flight_Conditions_Dataset.pdf",
      ],
      sourceAuthority: "nasa_official",
      sourceType: "nasa",
      excerpt: "Health-gate replay should carry source label, canonical URL, and section context so operational decisions stay auditable instead of benchmark-only.",
      rank: 2,
      provider: "fastembed",
      score: 1.1,
    },
  ],
  actions: [
    "Open a maintenance review with the current cycle and NASA RUL label of 112 cycles.",
    "Keep the asset in monitoring mode; this is not an immediate stop condition.",
  ],
  ticket: { id: 1007, title: "Review FD001-UNIT-001 diagnostic run", status: "open" },
  usage: { model: "gpt-5.4-nano", inputTokens: 609, outputTokens: 503, totalTokens: 1112 },
};
